name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: njausteve/hello-world-javascript-action/@master
        with:
          who-to-greet: "njauseteviedd"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Branch name
        id: branch
        run: echo ${BRANCH_NAME} 
